const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"糕点专栏类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryGaodianzhuanlan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"每日推荐类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryMeirituijain"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"面食菜谱类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryMianshicaipu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"面食文化类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryMianshiwenhua"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"新闻类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryNews"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"社区文章类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryShequxinxi"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"论坛信息管理",
                        "menuJump":"列表",
                        "tableName":"forum"
                    }
                ],
                "menu":"论坛信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"糕点专栏管理",
                        "menuJump":"列表",
                        "tableName":"gaodianzhuanlan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"糕点专栏留言管理",
                        "menuJump":"列表",
                        "tableName":"gaodianzhuanlanLiuyan"
                    }
                ],
                "menu":"糕点专栏管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"每日推荐管理",
                        "menuJump":"列表",
                        "tableName":"meirituijain"
                    }
                ],
                "menu":"每日推荐管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"面食菜谱管理",
                        "menuJump":"列表",
                        "tableName":"mianshicaipu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"面食菜谱留言管理",
                        "menuJump":"列表",
                        "tableName":"mianshicaipuLiuyan"
                    }
                ],
                "menu":"面食菜谱管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"面食文化管理",
                        "menuJump":"列表",
                        "tableName":"mianshiwenhua"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"面食文化留言管理",
                        "menuJump":"列表",
                        "tableName":"mianshiwenhuaLiuyan"
                    }
                ],
                "menu":"面食文化管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"新闻动态管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"新闻动态管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"社区信息管理",
                        "menuJump":"列表",
                        "tableName":"shequxinxi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"文章留言管理",
                        "menuJump":"列表",
                        "tableName":"shequxinxiLiuyan"
                    }
                ],
                "menu":"社区信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "删除"
	                    ],
	                    "menu":"论坛信息管理",
	                    "menuJump":"列表",
	                    "tableName":"forum"
	                }
	            ],
	            "menu":"论坛信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                    ],
	                    "menu":"糕点专栏管理",
	                    "menuJump":"列表",
	                    "tableName":"gaodianzhuanlan"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"糕点专栏留言管理",
	                    "menuJump":"列表",
	                    "tableName":"gaodianzhuanlanLiuyan"
	                }
	            ],
	            "menu":"糕点专栏管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                    ],
	                    "menu":"每日推荐管理",
	                    "menuJump":"列表",
	                    "tableName":"meirituijain"
	                }
	            ],
	            "menu":"每日推荐管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                    ],
	                    "menu":"面食菜谱管理",
	                    "menuJump":"列表",
	                    "tableName":"mianshicaipu"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
						],
	                    "menuJump":"列表",
	                    "tableName":"mianshicaipuLiuyan"
	                }
	            ],
	            "menu":"面食菜谱管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                    ],
	                    "menu":"面食文化管理",
	                    "menuJump":"列表",
	                    "tableName":"mianshiwenhua"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"面食文化留言管理",
	                    "menuJump":"列表",
	                    "tableName":"mianshiwenhuaLiuyan"
	                }
	            ],
	            "menu":"面食文化管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                    ],
	                    "menu":"新闻动态管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"新闻动态管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"社区信息管理",
	                    "menuJump":"列表",
	                    "tableName":"shequxinxi"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"文章留言管理",
	                    "menuJump":"列表",
	                    "tableName":"shequxinxiLiuyan"
	                }
	            ],
	            "menu":"社区信息管理"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"用户",
	    "tableName":"yonghu"
	}
]
    }
}
export default menu;